### ISSUE TITLE
barcode reader

### ISSUE THREAD

**Issue by sidharthanc** [svlabs/playbook#1]
how to read the barcode content using ruby code?
generated the barcode..but i dont know how to retrieve the information in barcode by using ruby code.
by using barcodescanner i got the error as  "cannot load such file -- barcodescanner (LoadError)"
how can i use barcode scanner without this error?
pls help me..

**Comment by sidharthanc** [comment]
require 'rubygems'
require 'barcodescanner'
result = BarcodeScanner.process_image_file("E:\sidhu\barcode.png")

## puts "result is"+result

this is my ruby code...during run this code.. i got the above error
"cannot load such file -- barcodescanner (LoadError)"
pls help to do barcode reading....
Regards,
sidharthan

**Comment by vishnugopal** [comment]
Have no clue why this was posted here. Closing.
